// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvppazqkoonwnrrfeorq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cHBhenFrb29ud25ycmZlb3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDA5NzEsImV4cCI6MjA2NjY3Njk3MX0.9Wvs4MAhurqY9Y7gA2C_RebDJJLCTa8KDaICm5TKJkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);